Just data exploration for future

In [1]:
import fastf1

session = fastf1.get_session(2024, "Bahrain", "R")
session.load()

results = session.results

results.head()

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) C:\Users\Admin\AppData\Local\Temp\fastf1
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671c6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:31:44.742000,Finished,26.0,57.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671c6,red_bull,Sergio,Perez,Sergio Perez,...,2.0,2,5.0,NaT,NaT,NaT,0 days 00:00:22.457000,Finished,18.0,57.0
55,55,C SAINZ,SAI,sainz,Ferrari,e8002d,ferrari,Carlos,Sainz,Carlos Sainz,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:25.110000,Finished,15.0,57.0
16,16,C LECLERC,LEC,leclerc,Ferrari,e8002d,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,4,2.0,NaT,NaT,NaT,0 days 00:00:39.669000,Finished,12.0,57.0
63,63,G RUSSELL,RUS,russell,Mercedes,27f4d2,mercedes,George,Russell,George Russell,...,5.0,5,3.0,NaT,NaT,NaT,0 days 00:00:46.788000,Finished,10.0,57.0

In [2]:
results.columns
results[[
    "Abbreviation",
    "TeamName",
    "Position",
    "GridPosition",
    "Status"
]]

   Abbreviation         TeamName  Position  GridPosition    Status
1           VER  Red Bull Racing       1.0           1.0  Finished
11          PER  Red Bull Racing       2.0           5.0  Finished
55          SAI          Ferrari       3.0           4.0  Finished
16          LEC          Ferrari       4.0           2.0  Finished
63          RUS         Mercedes       5.0           3.0  Finished
4           NOR          McLaren       6.0           7.0  Finished
44          HAM         Mercedes       7.0           9.0  Finished
81          PIA          McLaren       8.0           8.0  Finished
14          ALO     Aston Martin       9.0           6.0  Finished
18          STR     Aston Martin      10.0          12.0  Finished
24          ZHO      Kick Sauber      11.0          17.0    Lapped
20          MAG     Haas F1 Team      12.0          15.0    Lapped
3           RIC               RB      13.0          14.0    Lapped
22          TSU               RB      14.0          11.0    Lapped
23          ALB         Williams      15.0          13.0    Lapped
27          HUL     Haas F1 Team      16.0          10.0    Lapped
31          OCO           Alpine      17.0          19.0    Lapped
10          GAS           Alpine      18.0          20.0    Lapped
77          BOT      Kick Sauber      19.0          16.0    Lapped
2           SAR         Williams      20.0          18.0    Lapped

In [ ]:
results[
    ["Abbreviation", "GridPosition", "Position"] #Сравнение финишной позиции со стартовой
].sort_values("Position").head(10)

   Abbreviation  GridPosition  Position
1           VER           1.0       1.0
11          PER           5.0       2.0
55          SAI           4.0       3.0
16          LEC           2.0       4.0
63          RUS           3.0       5.0
4           NOR           7.0       6.0
44          HAM           9.0       7.0
81          PIA           8.0       8.0
14          ALO           6.0       9.0
18          STR          12.0      10.0

In [ ]:
results["PositionsGained"] = (
    results["GridPosition"] - results["Position"] 
) #Фьючер для подсчета позиций, которые гонщик выиграл или проиграл относительно старта

In [8]:
results[
    ["Abbreviation", "GridPosition", "Position", "PositionsGained"]
].sort_values(
    "PositionsGained",
    ascending=False
)

   Abbreviation  GridPosition  Position  PositionsGained
24          ZHO          17.0      11.0              6.0
11          PER           5.0       2.0              3.0
20          MAG          15.0      12.0              3.0
44          HAM           9.0       7.0              2.0
31          OCO          19.0      17.0              2.0
10          GAS          20.0      18.0              2.0
18          STR          12.0      10.0              2.0
55          SAI           4.0       3.0              1.0
4           NOR           7.0       6.0              1.0
3           RIC          14.0      13.0              1.0
81          PIA           8.0       8.0              0.0
1           VER           1.0       1.0              0.0
16          LEC           2.0       4.0             -2.0
63          RUS           3.0       5.0             -2.0
2           SAR          18.0      20.0             -2.0
23          ALB          13.0      15.0             -2.0
14          ALO           6.0       9.0             -3.0
22          TSU          11.0      14.0             -3.0
77          BOT          16.0      19.0             -3.0
27          HUL          10.0      16.0             -6.0